version: '3'

services:

  postgres-tgl:
      image: "postgres"
      container_name: postgres-tgl
      ports:
        - "5433:5432"
      environment:
        POSTGRES_USER: topgunlab
        POSTGRES_PASSWORD: topgunlab
        POSTGRES_DATABASES: topgunlab
